server:
  port: 8063
  servlet:
    context-path: /opencart

spring:
  application:
    name: gatekeeper-server
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# Run the custom API Gateway Auth Filter and verify JWT
moto-cart:
  security:
    header-auth:
      enabled: false

jwt:
  secret:
    public: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm9U1Sa8fGpbvpnJ17NZGIzLCJd1Vl3BPba67Tdz64f/AkIRChbPBaarCBmqd9MpS9N3o4lQCZJcTFisQ8fqLD+n+wFprQTE5pITTXUz3j1AlY14+UvHFsCxJ6nxJMcONzT9pyX8iy8YyFqjOyp1sjFysAsa7de7qmDcAKhskMC9KhnSQAciTgS7LZwc446BC4UHjrbyeQZl5oeBBiaGC6ZySLRz2H0Pl+emo6yR+y8Dt6QDOyGIA/f4xJetEVCXNx95h8UH7mQGoVo6Wo30QAksFRCT4tKrFfq4NXFVQ6/Kyeu4fsZvA1bmeUKur9xXt39qDlJaFxa5qHyiEg6z2ZQIDAQAB

logging:
  level:
    root: INFO