server:
  port: 8063
  servlet:
    context-path: /opencart

spring:
  application:
    name: gatekeeper-server
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    root: INFO