server:
  port: 8063
  servlet:
    context-path: /opencart

spring:
  application:
    name: gatekeeper-server
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# Run the custom API Gateway Auth Filter and verify JWT
moto-cart:
  security:
    header-auth:
      enabled: false

jwt:
  secret:
    public: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCacbukuJ3zxH6cYRkUI+nv5Qgp9Ti2FRUe2eMtetjJdNEltf4G1b7KPVi9ciaWN9Eexq6rn8n8td+DijxDX3SIHQVPwYJHq513WFy2T4OBQt6U3AhbKHGkEaZLTpQr8mK4koUQRbsE+Nkc++lxjpntkhawbvlrFtlA+w1Ykb7JawIDAQAB

logging:
  level:
    root: INFO